import { StyleSheet } from "react-native";

export const registerStyles = StyleSheet.create({
  container: { flexGrow: 1, backgroundColor: "#fff" },
  topSection: { width: "100%", height: 500, overflow: "hidden" },
  backgroundImage: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
  },
  title: { fontSize: 32, color: "#fff", fontWeight: "bold", marginTop: 200 },
  form: { marginTop: -40, paddingHorizontal: 25 },
  inputContainer: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "#ccc",
    marginBottom: 12,
    paddingHorizontal: 10,
    elevation: 3,
    backgroundColor: "#fff",
    borderRadius: 8,
  },
  imageContainer: {
    position: "absolute",
    top: 0,
    left: 250,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  headerImage: { width: 200, height: 100 },
  welcomeSection: { alignItems: "center", marginTop: 105, marginBottom: 50 },
  welcomeText: { fontSize: 48, fontWeight: "800", color: "#00A6E8" },
  subtitleText: { fontSize: 15, color: "#666" },
  inputpass: { flex: 1, height: 50, color: "#000" },
  input: {
    height: 50,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 8,
    marginBottom: 12,
    elevation: 3,
  },
  inputIcon: { marginRight: 10 },
  button: {
    backgroundColor: "#00A6E8",
    padding: 15,
    borderRadius: 15,
    alignItems: "center",
    marginTop: 5,
  },
  buttonText: { color: "#fff", fontSize: 18, fontWeight: "600" },
  footerText: {
    textAlign: "center",
    marginTop: 20,
    marginBottom: 60,
    fontSize: 14,
    color: "#777",
  },
  loginText: { color: "#00A6E8", fontWeight: "600" },
  error: { color: "red", marginBottom: 10, textAlign: "center" },
});
