export type RootStackParamList = {
  Welcome: undefined;
  Onboarding: undefined;
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  VerifyCode: { email: string };
  ResetPassword: { email: string; code: string };
  Home: undefined;
  Dashboard: undefined;
  Hotels: { countryId?: string };
  HotelDetails: { id: string };
  Flights: { destination: string };
  Countries: undefined;
  CountriesList: undefined;
  CountryDetails: { id: number | string };
  Profile: undefined;
  FlightDetails: { id: number | string };
  Deals: undefined;
  AIDiscovery: undefined;
  TripPlanner: undefined;
  Wishlist: undefined;
  ManageFlights: undefined;
  ManageHotels: undefined;
  ManageUsers: undefined;
  ContactUs: undefined;
  Search: undefined;
  Reports: undefined;
  AdminMessages: undefined;
};